name: StaffPlusPlusDiscord
main: be.garagepoort.staffplusplus.discord.StaffPlusPlusDiscord
author: garagepoort
version: ${project.version}
api-version: 1.13
depend: [StaffPlus]
softdepend: [DiscordSRV, PlaceholderAPI]
commands:
    staffplusplusdiscord:
        description: reload the plugin
        usage: /<command> [reload]
        aliases: [staffplusplusdiscord]
